AllCops:
  Exclude:
    - 'bin/*'

Metrics/LineLength:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Bundler/OrderedGems:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

